name: saly_ui_kit
description: "Saly UI Kit."
version: 0.0.2

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_gen: ^5.11.0
  flutter_svg: ^2.2.0
  pinput: ^5.0.1
  reactive_forms: ^18.1.1

dev_dependencies:
  build_runner: ^2.6.0
  flutter_gen_runner: ^5.11.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/src/gen/
  line_length: 120
  assets:
    outputs:
      class_name: SalyAssets
      package_parameter_enabled: true
  colors:
    inputs:
      - assets/colors/light_colors.xml
  integrations:
    image: true
    flutter_svg: true
  fonts:
    enabled: true

flutter:
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/source_sans_pro/SourceSansPro-Black.ttf
          weight: 800
        - asset: assets/fonts/source_sans_pro/SourceSansPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/source_sans_pro/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/source_sans_pro/SourceSansPro-Regular.ttf
          weight: 400
